Mlflow server
interTwin-eu/T6.5-AI-and-ML pull request #49
Opened 2023-06-02 12:59 UTC by matbun

# Summary

---

**Related issue :**

2023-06-02 13:08 UTC, matbun commented
@MrGweep this is a working example of how to use MLFLow server with HTTP communication. See if/how you want to merge

2023-06-02 14:27 UTC, MrGweep requested changes
Tried it out and works fine. One test failed cause of a type, so I suggested it in the comments.

2023-06-05 07:17 UTC, MrGweep approved these changes

2023-06-05 07:45 UTC, MrGweep approved these changes

2023-06-05 07:46 UTC, merged